version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      timeout: 20s
      retries: 10
volumes:
  db: