version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "5333:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      timeout: 20s
      retries: 10
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/testData.sql:/docker-entrypoint-initdb.d/policy.sql
volumes:
  db: