spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: LinguisticSummariesOfDatabases
  datasource:
    username: ${POSTGRES_USER:#{user}}
    password: ${POSTGRES_PASSWORD:#{password}}
    url: ${POSTGRES_URL}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect